### ISSUE TITLE
Release cycle / access

### ISSUE THREAD

**Issue by levithomason** [mikeal/watch#102]
@finnp or @mikeal I don't have access to release on NPM:

```shell
$ npm access ls-collaborators watch
{
  "mikeal": "read-write",
  "finnpauls": "read-write"
}
```

Would one of you mind releasing the latest updates or adding me to the collaborators?

>https://www.npmjs.com/~levithomason

**Comment by mikeal** [comment]
hrm... something isn't working

```
% npm owner add levithomason watch                                                                                     ~
npm ERR! registry error parsing json
```

**Comment by levithomason** [comment]
Ah, I saw this and fixed it in [this commit](https://github.com/mikeal/watch/pull/99/commits/5ab4c62a1affaa64d3badd17debefcc7b3230ab5) in the `--include` PR.  The `engines` entry is not valid. See the validator [here](http://package-json-validator.com/):


```json
{
  "valid": false,
  "errors": [
    "Type for field engines, was expected to be object, not object"
  ],
  "warnings": [
    "Missing recommended field: contributors"
  ]
}
```

I'll make a separate PR just for this fix first...

**Comment by levithomason** [comment]
Done, should work now!

**Comment by mikeal** [comment]
still getting the same error trying to add you as an owner :(

**Comment by levithomason** [comment]
You'd have to publish the updated package first I bet.  Then, add me.  Otherwise, I've only fixed the package.json here on GitHub, but npm is the one yelling about it.

**Comment by levithomason** [comment]
Confirmed, the old package.json is still the published one.  Could you publish a new version with the latest repo and then try adding me?

Here's the bad field:

```shell
› npm view watch version
0.17.1

› npm view watch engines
[ 'node >=0.1.95' ]
```

**Comment by mikeal** [comment]
ok, added now :)

**Comment by levithomason** [comment]
woop! thanks much :D
